language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt512base  qt512tools libgl-dev
    - source /opt/qt*/bin/qt*-env.sh

script: 
  - mkdir appdir appdir/usr appdir/usr/share appdir/usr/share/applications
  - cp  byteicon.desktop appdir/usr/share/applications
  - qmake PREFIX=/usr
  - make -j$(nproc)
  - make INSTALL_ROOT=appdir install ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ls /home/travis/build/Bytespeicher/BytespeicherTrayIcon
  - cp /home/travis/build/Bytespeicher/BytespeicherTrayIcon/byteicon appdir/usr/share/applications
  - cp res/byteicon.png appdir/usr/share/applications
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: byteicon-$(git rev-parse --short HEAD)-x86_64.AppImage
  skip_cleanup: true
  draft: true
  on:
    repo: Bytespeicher/BytespeicherTrayIcon
    branches:
      only:
        - master
